"""Backend-neutral simulator protocol.

Every physics engine adapter (PyBullet first, others later) implements this
protocol. Code outside `backends/` must only depend on this interface, never
on a specific engine.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from creature_lab.schema import CreatureSpec, FrameState, TaskSpec


@runtime_checkable
class SimBackend(Protocol):
    def build(self, creature: CreatureSpec, task: TaskSpec, *, seed: int | None = None) -> None: ...
    def reset(self) -> None: ...
    def step(self, dt: float) -> FrameState: ...
    def observe(self) -> FrameState: ...
    def apply_motor_targets(self, targets: dict[str, float]) -> None: ...
    def apply_joint_control(self, targets: dict[str, float], mode: str = "position") -> None: ...
    def damage_part(self, part_id: str) -> None: ...
    def score_summary(self) -> dict[str, float]: ...
    def close(self) -> None: ...
